CREATE TABLE CUSTTABLE (
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE,
    PHONE_NO NUMBER,
    ADDRESS VARCHAR2(50)
); 
INSERT INTO CUSTTABLE VALUES (1,'Abi','abi@gmail.com',1234567890,'Ramapuram Chennai');

INSERT INTO CUSTTABLE VALUES (2,'Anu','anu@gmail.com',0987654321,'Madurai');

INSERT INTO CUSTTABLE VALUES (3,'Ravi','ravi@gmail.com',9087654321,'Chengalpattu');

INSERT INTO CUSTTABLE VALUES (4,'Karthik','karthik@gmail.com',9876543210,'Coimbatore');

INSERT INTO CUSTTABLE VALUES (5,'Priya','priya@gmail.com',8765432109,'Salem');

INSERT INTO CUSTTABLE VALUES (6,'Divya','divya@gmail.com',7654321098,'Trichy');

INSERT INTO CUSTTABLE VALUES (7,'Arun','arun@gmail.com',6543210987,'Vellore');

INSERT INTO CUSTTABLE VALUES (8,'Meena','meena@gmail.com',9432109876,'Tirunelveli');

INSERT INTO CUSTTABLE VALUES (9,'Suresh','suresh@gmail.com',9321098765,'Erode');

INSERT INTO CUSTTABLE VALUES (10,'Nisha','nisha@gmail.com',9210987654,'Thanjavur');

-- DISPLAY RECORDS

SELECT * FROM CUSTTABLE;

-- UPDATE RECORD

UPDATE CUSTTABLE
SET ADDRESS = 'Vellore'
WHERE CID = 10;

-- DISPLAY UPDATED RECORDS

SELECT * FROM CUSTTABLE;

-- DELETE RECORD

DELETE FROM CUSTTABLE
WHERE CID = 9;

-- DISPLAY FINAL RECORDS

SELECT * FROM CUSTTABLE;

COMMIT;
